---

email: gpii-ops@gpii.org
env_runtime: linux-desktop

apps:
  - app_name: gpii-universal
    software_stack: nodejs
    nodejs_app_git_clone: false # Sorry, this variable should be renamed. We will get the code from the shared folder.
    folder:
      dest: /app/gpii-universal
      src: .
    run_in: fedora
    setup:
      - "mkdir -p node_modules"
      - "rsync -a . node_modules/universal" #universal requires universal itself in node_modules
      - npm install
      - "sudo npm install -g testem"
    test_cmds:
      - "npm test"
      - "testem ci --file tests/web/testem_qi.json"
      - "node tests/ProductionConfigTests.js"

