---

email: gpii-ops@gpii.org
env_runtime: linux-desktop

apps:
  - app_name: gpii-universal
    software_stack: nodejs
    nodejs_app_git_clone: false # Sorry, this variable should be renamed. We will get the code from the shared folder.
    folder:
      dest: /app/gpii-universal
      src: .
    run_in: fedora
    setup:
      - npm install
      - "sudo npm install -g testem"
    test_cmds:
      - "mkdir -p node_modules"
      - "cp -r /app/gpii-universal /tmp/universal-tmp"
      - "rm -fr /tmp/universal-tmp/node_modules"
      - "mv /tmp/universal-tmp /app/gpii-universal/node_modules/universal"
      - "npm test"
      - "testem ci --file tests/web/testem_qi.json"
      - "node tests/ProductionConfigTests.js"

